# Generated by Django 4.1.6 on 2023-02-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
