# Generated by Django 4.1.6 on 2023-02-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
