# Generated by Django 4.1.6 on 2023-02-06 03:29

from django.db import migrations, models


def create_data(apps, schema_editor):
    ActivityType = apps.get_model('core', 'ActivityType')
    ActivityType.objects.create(id=1, type="Recreational")
    ActivityType.objects.create(id=2, type="Educational")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity_link'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
